### ISSUE TITLE
I  get the depth but cannot select the volume in this module..

### ISSUE THREAD

**Issue by LiZhenzhuBlog** [PerkLab/DepthImageToPointCloud#3]
I  get the depth image but cannot select the InPut volume in this module..

**Comment by ColtonBarr** [comment]
The Input Volume selector expects a volume node of the class vtkMRMLScalarVolumeNode, so your image is likely not of this class. How are you getting the depth image into 3D Slicer? I'm able to use depth images in the module by streaming them from an Intel Realsense using [PLUS Server](https://plustoolkit.github.io/) and the OpenIGTLinkIF module in the [SlicerOpenIGTLink extension](https://github.com/openigtlink/SlicerOpenIGTLink).

**Comment by timeanddoctor** [comment]
Yes, I stream the depth image into the slicer by plus.  The volume seems to be a vector volume defaluty so I cannot select the inputvolume. How to change this to a scalarvolume? and the image seems to be a single one "z"=1.
![image](https://user-images.githubusercontent.com/28825816/93879596-8cb0fc00-fd0e-11ea-89dc-86e93aabf01f.png)

**Comment by ColtonBarr** [comment]
Try setting the _UseRealSenseColorizer_ parameter in the plus .xml configuration file to "FALSE" if it is not already. If you're using the example RealSense config file from [here](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceIntelRealSense.html) then it may be set to "TRUE", which will stream depth images as vectors.
